const cookies = {
  AGENT_RNO: 'USER_AGENTRNO',
  AGENT_NO: 'USER_AGENTNO',
  AGENT_NAME: 'USER_AGENTNAME',

  USER_ID: 'USER_ID',
  USER_CODE: 'USER_CODE',
  USER_NAME: 'USER_NAME',

  USER_M_AGENTNO: 'USER_M_AGENTNO',
  USER_M_ADMIN: 'USER_M_ADMIN',
  USER_MMDIV: 'USER_MMDIV',

  SYS_DIV: 'USER_SYSDIV',
  SHOP_DIV: 'USER_SHOPDIV',
  EGG_DIV: 'USER_EGGDIV',
  AMT_DIV: 'USER_AMTDIV',
  CONNECT_DIV: 'USER_CONNECTDIV',

  POINT_CNT: 'USER_POINTDIV',
  POINT_AMT_CNT: 'USER_APOINTDIV'
};

export default cookies;
